# Generated by Django 5.2 on 2025-05-07 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supplier_created_at_supplier_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='street_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='street_no',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='zipcode',
            field=models.CharField(default=None, max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
