# Generated by Django 5.2 on 2025-05-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_supplier_city_supplier_street_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_id',
            field=models.CharField(default='UNASSIGNED', max_length=50),
        ),
    ]
